--
COL tablespace		HEAD 'Tablespace Name'	FORMAT a25
COL initial_ext		HEAD 'Initial Extent'	FORMAT 999,999,999,999
COL next_ext		HEAD 'Next Extent'		FORMAT 999,999,999,999
COL max_ext			HEAD 'Max Extent'		FORMAT 999,999,999,999
COL pct_increase	HEAD 'Percent Increase'	FORMAT 90.09
--
SELECT
	TABLESPACE_NAME AS TABLESPACE,
	INITIAL_EXTENT AS INITIAL_EXT,
	NEXT_EXTENT AS NEXT_EXT,
	MIN_EXTENTS AS MIN_EXT,
	MAX_EXTENTS AS MAX_EXT,
	PCT_INCREASE
FROM
	DBA_TABLESPACES
ORDER BY
	TABLESPACE
/
