DROP DATABASE IF EXISTS alerts;
CREATE DATABASE alerts;
USE alerts;
-- (C) Copyright 2008, 2012 IBM Corporation

-- Create the status table
CREATE TABLE status
(
	ACTIONTIME      DATETIME NOT NULL,
	ACTIONCODE      CHAR(1) NOT NULL,
	IDENTIFIER      VARCHAR(255) NULL,
	SERIAL          NUMERIC(16) NULL,
	NODE            VARCHAR(64) NULL,
	NODEALIAS       VARCHAR(64) NULL,
	MANAGER         VARCHAR(64) NULL,
	AGENT           VARCHAR(64) NULL,
	ALERTGROUP      VARCHAR(255) NULL,
	ALERTKEY        VARCHAR(255) NULL,
	ALERTSOURCE     VARCHAR(64) NULL,
	SEVERITY        NUMERIC(1) NULL,
	SUMMARY         VARCHAR(255) NULL,
	STATECHANGE     DATETIME NULL,
	FIRSTOCCURRENCE DATETIME NULL,
	LASTOCCURRENCE  DATETIME NULL,
	INTERNALLAST    DATETIME NULL,
	POLL            NUMERIC(16) NULL,
	TYPE            NUMERIC(16) NULL,
	TALLY           NUMERIC(16) NULL,
	CLASS           NUMERIC(16) NULL,
	GRADE           NUMERIC(16) NULL,
	LOCATION        VARCHAR(64) NULL,
	OWNERUID        NUMERIC(16) NULL,
	OWNERGID        NUMERIC(16) NULL,
	ACKNOWLEDGED    NUMERIC(16) NULL,
	FLASH           NUMERIC(16) NULL,
	EVENTID		VARCHAR(255) NULL,
	EXPIRETIME	NUMERIC(16) NULL,
	PROCESSREQ	NUMERIC(16) NULL,
	SUPPRESSESCL	NUMERIC(16) NULL,
	CUSTOMER	VARCHAR(64) NULL,
	SERVICE		VARCHAR(64) NULL,
	PHYSICALSLOT	NUMERIC(16) NULL,
	PHYSICALPORT	NUMERIC(16) NULL,
	PHYSICALCARD	VARCHAR(64) NULL,
	TASKLIST	NUMERIC(16) NULL,
	NMOSSERIAL	VARCHAR(64) NULL,
	NMOSOBJINST	NUMERIC(16) NULL,
	NMOSCAUSETYPE	NUMERIC(16) NULL,
	NMOSDOMAINNAME	VARCHAR(64) NULL,
	NMOSENTITYID	NUMERIC(16) NULL,
	NMOSMANAGEDSTATUS	NUMERIC(16) NULL,
	LOCALNODEALIAS	VARCHAR(64) NULL,
	LOCALPRIOBJ	VARCHAR(255) NULL,
	LOCALSECOBJ	VARCHAR(255) NULL,
	LOCALROOTOBJ	VARCHAR(255) NULL,
	REMOTENODEALIAS	VARCHAR(64) NULL,
	REMOTEPRIOBJ	VARCHAR(255) NULL,
	REMOTESECOBJ	VARCHAR(255) NULL,
	REMOTEROOTOBJ	VARCHAR(255) NULL,
	X733EVENTTYPE	NUMERIC(16) NULL,
	X733PROBABLECAUSE NUMERIC(16) NULL,
	X733SPECIFICPROB VARCHAR(64) NULL,
	X733CORRNOTIF	VARCHAR(255) NULL,
	SERVERNAME      VARCHAR(64) NOT NULL,
	SERVERSERIAL    NUMERIC(16) NOT NULL,
	PRIMARY KEY ( ACTIONTIME, ACTIONCODE, SERVERSERIAL, SERVERNAME, FIRSTOCCURRENCE )
) PARTITION BY RANGE COLUMNS ( FIRSTOCCURRENCE ) (
	PARTITION p201301 VALUES LESS THAN ( '2013-02-01' ),
	PARTITION p201302 VALUES LESS THAN ( '2013-03-01' ),
	PARTITION p201303 VALUES LESS THAN ( '2013-04-01' ),
	PARTITION p201304 VALUES LESS THAN ( '2013-05-01' ),
	PARTITION p201305 VALUES LESS THAN ( '2013-06-01' ),
	PARTITION p201306 VALUES LESS THAN ( '2013-07-01' ),
	PARTITION p201307 VALUES LESS THAN ( '2013-08-01' ),
	PARTITION p201308 VALUES LESS THAN ( '2013-09-01' ),
	PARTITION p201309 VALUES LESS THAN ( '2013-10-01' ),
	PARTITION p201310 VALUES LESS THAN ( '2013-11-01' ),
	PARTITION p201311 VALUES LESS THAN ( '2013-12-01' ),
	PARTITION p201312 VALUES LESS THAN ( '2014-01-01' ),
	PARTITION pMAXVAL VALUES LESS THAN ( MAXVALUE )
);

CREATE TABLE journal
(
	SERIAL  NUMERIC(16) NOT NULL,
	UID     NUMERIC(16) NOT NULL,
	CHRONO  DATETIME NOT NULL,
	TEXT1   VARCHAR(255) NULL,
	TEXT2   VARCHAR(255) NULL,
	TEXT3   VARCHAR(255) NULL,
	TEXT4   VARCHAR(255) NULL,
	TEXT5   VARCHAR(255) NULL,
	TEXT6   VARCHAR(255) NULL,
	TEXT7   VARCHAR(255) NULL,
	TEXT8   VARCHAR(255) NULL,
	TEXT9   VARCHAR(255) NULL,
	TEXT10  VARCHAR(255) NULL,
	TEXT11  VARCHAR(255) NULL,
	TEXT12  VARCHAR(255) NULL,
	TEXT13  VARCHAR(255) NULL,
	TEXT14  VARCHAR(255) NULL,
	TEXT15  VARCHAR(255) NULL,
	TEXT16  VARCHAR(255) NULL,
	SERVERNAME VARCHAR(64) NOT NULL,
	SERVERSERIAL NUMERIC(16) NOT NULL,
	PRIMARY KEY ( SERVERSERIAL, SERVERNAME, CHRONO )
);

CREATE TABLE details
(
	IDENTIFIER VARCHAR(255),
	ATTRVAL    NUMERIC(16),
	SEQUENCE   NUMERIC(16),
	NAME       VARCHAR(255),
	DETAIL     VARCHAR(255),
	SERVERNAME VARCHAR(64) NOT NULL,
	SERVERSERIAL NUMERIC(16) NOT NULL,
	PRIMARY KEY ( SERVERSERIAL, SERVERNAME, SEQUENCE )
);

CREATE TABLE severity
(
	ATTRVAL		NUMERIC(16),
	NAME		VARCHAR(16),
	PRIMARY KEY ( ATTRVAL )
);

CREATE TABLE types
(
	ATTRVAL		NUMERIC(16),
	NAME		VARCHAR(24),
	PRIMARY KEY ( ATTRVAL )
);

CREATE TABLE suppress_escalate
(
	ATTRVAL		NUMERIC(16),
	NAME		VARCHAR(18),
	PRIMARY KEY ( ATTRVAL )
);

INSERT INTO severity ( ATTRVAL, NAME ) VALUES ( 0, 'Clear' );
INSERT INTO severity ( ATTRVAL, NAME ) VALUES ( 1, 'Indeterminate' );
INSERT INTO severity ( ATTRVAL, NAME ) VALUES ( 2, 'Informational' );
INSERT INTO severity ( ATTRVAL, NAME ) VALUES ( 3, 'Minor' );
INSERT INTO severity ( ATTRVAL, NAME ) VALUES ( 4, 'Major' );
INSERT INTO severity ( ATTRVAL, NAME ) VALUES ( 5, 'Critical' );

INSERT INTO types ( ATTRVAL, NAME ) VALUES ( 0, 'Type Not Set' );
INSERT INTO types ( ATTRVAL, NAME ) VALUES ( 1, 'Problem' );
INSERT INTO types ( ATTRVAL, NAME ) VALUES ( 2, 'Resolution' );
INSERT INTO types ( ATTRVAL, NAME ) VALUES ( 11, 'More Severe' );
INSERT INTO types ( ATTRVAL, NAME ) VALUES ( 12, 'Less Severe' );
INSERT INTO types ( ATTRVAL, NAME ) VALUES ( 13, 'Information' );

INSERT INTO suppress_escalate ( ATTRVAL, NAME ) VALUES ( 0, 'Normal' );
INSERT INTO suppress_escalate ( ATTRVAL, NAME ) VALUES ( 1, 'Escalated' );
INSERT INTO suppress_escalate ( ATTRVAL, NAME ) VALUES ( 2, 'Escalated-Level 2' );
INSERT INTO suppress_escalate ( ATTRVAL, NAME ) VALUES ( 3, 'Escalated-Level 3' );
INSERT INTO suppress_escalate ( ATTRVAL, NAME ) VALUES ( 4, 'Suppressed' );
INSERT INTO suppress_escalate ( ATTRVAL, NAME ) VALUES ( 5, 'Hidden' );
INSERT INTO suppress_escalate ( ATTRVAL, NAME ) VALUES ( 6, 'Maintenance' );
